@extends('layouts.guest')

@section('title', 'NEXA Desk — Support made simple')

@section('content')
<header class="landing-nav"><a class="brand brand-light" href="{{ route('home') }}"><span class="brand-symbol">N</span><span><strong>NEXA Desk</strong><small>SMART TICKETING & SERVICE HUB</small></span></a><nav class="landing-links"><a href="#features">Features</a><a href="#how-it-works">How it works</a><a href="#about">About</a></nav><div class="landing-actions"><a class="nav-login" href="{{ route('login') }}">Login</a><x-button href="{{ route('register') }}" variant="primary">Create account <span>→</span></x-button></div><button class="icon-button landing-menu" data-action="landing-menu" aria-label="Open menu">☰</button></header>
<main>
    <section class="hero-section"><div class="hero-copy"><div class="eyebrow"><span></span> SUPPORT THAT MOVES WORK FORWARD</div><h1>Support made<br><em>simple.</em></h1><p>Create, track, and manage your support tickets in one simple platform.</p><div class="hero-actions"><x-button href="{{ route('login') }}" variant="primary">Login <span>→</span></x-button><x-button href="{{ route('register') }}">Create account</x-button></div><div class="hero-proof"><div class="avatar-stack"><x-avatar name="Alex Morgan" size="tiny"/><x-avatar name="Jordan Lee" size="tiny"/><x-avatar name="Casey Park" size="tiny"/></div><span><strong>Support that feels human.</strong><small>One clear place to get help.</small></span></div></div><div class="hero-visual"><div class="hero-image" role="img" aria-label="Support team collaborating around a laptop"></div><div class="hero-note"><span class="live-dot"></span><span><strong>Support desk online</strong><small>Average first reply: 1.8 hours</small></span></div><div class="hero-ticket"><span class="mini-ticket-icon">✓</span><span><small>JUST RESOLVED</small><strong>VPN connection restored</strong></span><b>2m</b></div></div><div class="hero-orbit-label">BUILT FOR THE EVERYDAY FIX</div></section>
    <section class="trust-strip"><span>ONE WORKSPACE FOR EVERY REQUEST</span><div><b>IT & Operations</b><b>People & Finance</b><b>Security & Support</b></div></section>
    <section class="features-section section-wrap" id="features"><div class="section-heading"><span class="eyebrow">A BETTER WAY TO GET HELP</span><h2>Small details. <em>Big relief.</em></h2><p>Everything you need to ask a question, get an answer, and keep work moving.</p></div><div class="feature-grid">@foreach ([['＋', 'Easy ticket creation', 'Share the essentials and route your request to the right team.'], ['◷', 'Track your requests', 'See status, owner, and updates without chasing anyone down.'], ['↩', 'Talk with support', 'Keep the conversation and files together in one clear thread.'], ['◇', 'Find quick answers', 'Browse helpful guides before a small issue becomes a blocker.'], ['⚡', 'Get timely support', 'Priorities and service targets make urgent work visible.'], ['▤', 'Keep a ticket history', 'Revisit resolved requests and their steps whenever you need.']] as [$icon, $title, $description])<article class="feature-card"><span class="feature-icon">{{ $icon }}</span><h3>{{ $title }}</h3><p>{{ $description }}</p><span class="feature-arrow">↗</span></article>@endforeach</div></section>
    <section class="steps-section" id="how-it-works"><div class="section-wrap steps-layout"><div><span class="eyebrow">THREE STEPS, LESS BACK-AND-FORTH</span><h2>From question to<br><em>resolution.</em></h2><p class="section-intro">A calm, predictable path through every support request.</p><a class="text-cta" href="{{ route('register') }}">Create your account <span>→</span></a></div><div class="steps-list"><article><span>01</span><div><h3>Tell us what you need</h3><p>Choose a category, add context, and attach useful files.</p></div></article><article><span>02</span><div><h3>Follow the progress</h3><p>See who owns the request and reply in the same thread.</p></div></article><article><span>03</span><div><h3>Get back to work</h3><p>Receive a clear resolution and keep the history for later.</p></div></article></div></div></section>
    <section class="about-section section-wrap" id="about"><div class="about-stamp">N<span>×</span></div><div><span class="eyebrow">DESIGNED FOR REAL TEAMS</span><h2>Good support should<br>feel <em>straightforward.</em></h2><p>NEXA Desk gives customers and support teams a shared view of every request, from the first note to the final fix.</p><a class="text-cta" href="{{ route('login') }}">Explore the service hub <span>→</span></a></div><div class="about-metric"><strong>1.8<span>h</span></strong><small>average first response</small><div class="metric-line"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><small>Support is here when you need it.</small></div></section>
    <section class="landing-cta"><div><span class="eyebrow">A CLEARER SUPPORT EXPERIENCE STARTS HERE</span><h2>Let’s get your team<br><em>unstuck.</em></h2></div><x-button href="{{ route('register') }}" variant="light">Create your account <span>→</span></x-button></section>
</main><footer class="landing-footer"><a class="brand brand-light" href="{{ route('home') }}"><span class="brand-symbol">N</span><span><strong>NEXA Desk</strong><small>SMART TICKETING & SERVICE HUB</small></span></a><span>© 2026 NEXA Desk · Simple support, every day.</span><div><a href="#features">Features</a><a href="{{ route('login') }}">Login</a><a href="{{ route('admin.login') }}">Staff access</a></div></footer>
@endsection
