@extends('layouts.app')
@section('title', 'Create a Ticket — Problinx')
@section('page-title', 'Create ticket')
@section('content')
<div class="page-heading"><div><span class="eyebrow">WE'RE HERE TO HELP</span><h1>Create a support ticket</h1><p>Share a few details and we will route your request to the right team.</p></div><a class="subtle-link" href="{{ route('user.tickets') }}">← Back to tickets</a></div>
<div class="ticket-wizard"><div class="wizard-steps"><div class="wizard-step active" data-step-indicator="1"><span>1</span><strong>Category</strong></div><i></i><div class="wizard-step" data-step-indicator="2"><span>2</span><strong>Details</strong></div><i></i><div class="wizard-step" data-step-indicator="3"><span>3</span><strong>Attachments</strong></div><i></i><div class="wizard-step" data-step-indicator="4"><span>4</span><strong>Review</strong></div></div>
<form id="ticket-create-form" novalidate><section class="wizard-panel active" data-step="1"><div class="wizard-panel-heading"><span>STEP 1 OF 4</span><h2>What do you need help with?</h2><p>Choose the category that best fits your request.</p></div><div class="category-choice-grid">@foreach (['IT Support' => '◉', 'Hardware' => '▣', 'Software' => '▤', 'Network' => '⌁', 'Account' => '♙', 'Billing' => '$', 'Security' => '◇', 'Bug Report' => '⚑', 'Feature Request' => '＋', 'General Inquiry' => '?'] as $category => $icon)<label class="category-choice"><input type="radio" name="category" value="{{ $category }}" required><span class="category-choice-icon">{{ $icon }}</span><span><strong>{{ $category }}</strong><small>{{ $category === 'General Inquiry' ? 'Something else' : 'Get help with '.strtolower($category) }}</small></span><span class="choice-check">✓</span></label>@endforeach</div><div class="wizard-actions"><span></span><x-button type="button" variant="primary" data-next-step="2">Continue <span>→</span></x-button></div></section>
<section class="wizard-panel" data-step="2"><div class="wizard-panel-heading"><span>STEP 2 OF 4</span><h2>Tell us a little more</h2><p>A clear description helps us resolve your request sooner.</p></div><div class="form-two"><x-input label="Subject" name="subject" placeholder="Summarize the issue" required/><div class="field-wrap"><label for="ticket-priority">Priority</label><select class="field-input" id="ticket-priority" name="priority"><option>Low</option><option selected>Medium</option><option>High</option><option>Critical</option></select></div><div class="field-wrap"><label for="ticket-department">Department</label><select class="field-input" id="ticket-department" name="department"><option>IT Support</option><option>Technical Support</option><option>Billing</option><option>Security</option><option>Customer Service</option></select></div><x-input label="Device" name="device" placeholder="e.g. MacBook Pro or iPhone"/><x-input label="Location" name="location" placeholder="Office, floor or remote"/><div class="field-wrap full-field"><label for="ticket-description">Description<span class="required-mark">*</span></label><textarea class="field-input textarea" id="ticket-description" name="description" rows="5" placeholder="What happened? What did you expect? What have you tried?" required></textarea></div></div><div class="wizard-actions"><x-button type="button" data-prev-step="1">← Back</x-button><x-button type="button" variant="primary" data-next-step="3">Continue <span>→</span></x-button></div></section>
<section class="wizard-panel" data-step="3"><div class="wizard-panel-heading"><span>STEP 3 OF 4</span><h2>Add helpful files</h2><p>Attach a screenshot or document if it helps explain the issue. Files stay in this browser demo.</p></div><label class="upload-zone"><span class="upload-icon">↥</span><strong>Choose files to attach</strong><small>Images and documents · no upload is performed</small><input type="file" id="ticket-files" name="attachments" multiple accept="image/*,.pdf,.txt,.doc,.docx"></label><div id="attachment-preview" class="attachment-list"></div><div class="wizard-actions"><x-button type="button" data-prev-step="2">← Back</x-button><x-button type="button" variant="primary" data-next-step="4">Review ticket <span>→</span></x-button></div></section>
<section class="wizard-panel" data-step="4"><div class="wizard-panel-heading"><span>STEP 4 OF 4</span><h2>Review your request</h2><p>Everything look right? You can go back and make changes.</p></div><div class="review-ticket"><div class="review-row"><span>Category</span><strong data-review="category">Choose a category</strong></div><div class="review-row"><span>Subject</span><strong data-review="subject">—</strong></div><div class="review-row"><span>Priority</span><strong data-review="priority">Medium</strong></div><div class="review-row"><span>Description</span><p data-review="description">—</p></div><div class="review-row"><span>Attachments</span><strong data-review="attachments">None</strong></div></div><div id="ticket-form-error" class="form-alert" role="alert" hidden></div><div class="wizard-actions"><x-button type="button" data-prev-step="3">← Back</x-button><x-button type="submit" variant="primary">Submit ticket <span>→</span></x-button></div></section></form></div>
@endsection
