@extends('layouts.app')
@section('title', 'Support Console — Problinx')
@section('page-title', 'Overview')
@section('content')
@php($tickets = require resource_path('data/tickets.php'))
<div class="page-heading"><div><span class="eyebrow">MONDAY, SEPTEMBER 28, 2026</span><h1>Good morning, Jordan.</h1><p>Here is what is happening across the support desk.</p></div><a class="btn btn-secondary" href="{{ route('admin.reports') }}">Export report ↓</a></div>
<section class="stats-grid"><x-stat-card label="Total tickets" :value="count($tickets)" note="Across all teams" icon="▤"/><x-stat-card label="New tickets" :value="count(array_filter($tickets, fn ($t) => $t['status'] === 'New'))" note="Needs triage" icon="＋" tone="blue"/><x-stat-card label="Open tickets" :value="count(array_filter($tickets, fn ($t) => in_array($t['status'], ['Open', 'In Progress'], true)))" note="Being handled" icon="◷" tone="amber"/><x-stat-card label="Pending tickets" :value="count(array_filter($tickets, fn ($t) => $t['status'] === 'Waiting'))" note="Waiting on customer" icon="⌁" tone="blue"/><x-stat-card label="Escalated" :value="count(array_filter($tickets, fn ($t) => $t['status'] === 'Escalated'))" note="Priority attention" icon="⚑" tone="red"/><x-stat-card label="Resolved today" value="8" note="↑ 14% this week" icon="✓" tone="green"/></section>
<div class="admin-dashboard-grid"><div class="admin-dashboard-main"><section class="panel"><div class="panel-heading"><div><h2>Ticket volume</h2><p>Requests opened across the last 7 days</p></div><select class="filter-select"><option>Last 7 days</option><option>30 days</option></select></div><div class="volume-chart" aria-label="Ticket volume chart">@foreach ([['Mon',42], ['Tue',58], ['Wed',47], ['Thu',72], ['Fri',56], ['Sat',31], ['Sun',38]] as [$day, $height])<div class="volume-bar-group"><div class="volume-bar" style="--bar-height:{{ $height }}%"><i></i></div><small>{{ $day }}</small></div>@endforeach</div></section><section class="panel"><div class="panel-heading"><div><h2>Recent tickets</h2><p>Latest requests across all support teams</p></div><a class="subtle-link" href="{{ route('admin.tickets') }}">Manage tickets →</a></div><div class="table-scroll"><table class="data-table"><thead><tr><th>Ticket</th><th>Customer</th><th>Subject</th><th>Priority</th><th>Status</th><th>Agent</th></tr></thead><tbody>@foreach (array_slice($tickets, 0, 6) as $ticket)<tr><td><a href="{{ url('/admin/tickets/'.rawurlencode($ticket['id'])) }}">{{ $ticket['id'] }}</a></td><td>{{ $ticket['email'] }}</td><td class="truncate">{{ $ticket['subject'] }}</td><td><x-priority-badge :priority="$ticket['priority']"/></td><td><x-status-badge :status="$ticket['status']"/></td><td>{{ $ticket['agent'] }}</td></tr>@endforeach</tbody></table></div></section></div><aside class="admin-dashboard-side"><section class="panel"><div class="panel-heading"><div><h2>Urgent tickets</h2><p>Needs a closer look</p></div><span class="badge badge-priority-critical">{{ count(array_filter($tickets, fn ($t) => $t['priority'] === 'Critical')) }} critical</span></div>@foreach (array_slice(array_values(array_filter($tickets, fn ($t) => in_array($t['priority'], ['Critical', 'High'], true))), 0, 4) as $ticket)<a class="urgent-row" href="{{ url('/admin/tickets/'.rawurlencode($ticket['id'])) }}"><span class="urgent-dot"></span><span><strong>{{ $ticket['subject'] }}</strong><small>{{ $ticket['id'] }} · {{ $ticket['team'] }}</small></span><span>→</span></a>@endforeach</section><section class="panel"><div class="panel-heading"><div><h2>Recent activity</h2><p>Support team updates</p></div></div><div class="activity-feed"><x-timeline-item title="Jordan Lee assigned a ticket" time="8 minutes ago" icon="↗"/><x-timeline-item title="Alex Morgan resolved a VPN request" time="32 minutes ago" icon="✓"/><x-timeline-item title="New security article published" time="1 hour ago" icon="◇"/></div></section></aside></div>
@endsection
