@extends('layouts.app')
@section('title', 'Reports — NEXA Desk')
@section('page-title', 'Reports')
@section('content')
@php($tickets = require resource_path('data/tickets.php'))
<div class="page-heading"><div><span class="eyebrow">MEASURE WHAT MATTERS</span><h1>Reports & analytics</h1><p>Understand demand, resolution speed, and team performance.</p></div><button class="btn btn-secondary" data-action="export-report">Export CSV ↓</button></div>
<div class="report-filter-bar"><div class="segmented-control"><button class="active" data-report-range="Today">Today</button><button data-report-range="7 Days">7 days</button><button data-report-range="30 Days">30 days</button><button data-report-range="90 Days">90 days</button></div><span class="record-count">Sep 1 — Sep 28, 2026</span></div>
<section class="stats-grid"><x-stat-card label="Ticket volume" :value="count($tickets)" note="↑ 12% vs previous period" icon="▤"/><x-stat-card label="Resolution rate" value="87.4%" note="↑ 4.2% vs previous period" icon="✓" tone="green"/><x-stat-card label="Response time" value="1.8h" note="↓ 12% this month" icon="◷" tone="blue"/><x-stat-card label="Customer rating" value="4.7 / 5" note="142 customer responses" icon="★" tone="amber"/></section>
<div class="report-grid"><section class="panel"><div class="panel-heading"><div><h2>Ticket volume</h2><p>Tickets created and resolved</p></div></div><div class="volume-chart">@foreach ([['Mon',42], ['Tue',58], ['Wed',47], ['Thu',72], ['Fri',56], ['Sat',31], ['Sun',38]] as [$day, $height])<div class="volume-bar-group"><div class="volume-bar" style="--bar-height:{{ $height }}%"><i></i></div><small>{{ $day }}</small></div>@endforeach</div></section><section class="panel"><div class="panel-heading"><div><h2>Ticket categories</h2><p>Share by support area</p></div></div><div class="report-donut"><div></div><ul><li><i class="swatch teal"></i>IT Support <strong>32%</strong></li><li><i class="swatch blue"></i>Hardware <strong>24%</strong></li><li><i class="swatch amber"></i>Network <strong>19%</strong></li><li><i class="swatch green"></i>Other <strong>25%</strong></li></ul></div></section><section class="panel"><div class="panel-heading"><h2>Agent performance</h2></div><div class="performance-list">@foreach (array_slice(require resource_path('data/agents.php'), 0, 5) as $agent)<div><span>{{ $agent['name'] }}</span><strong>{{ $agent['resolved'] }} resolved</strong><div class="progress-track"><i style="--progress:{{ min($agent['resolved'] * 1.6, 100) }}%"></i></div></div>@endforeach</div></section><section class="panel"><div class="panel-heading"><h2>Resolution time</h2></div><div class="resolution-summary"><strong>8.4 <small>hours average</small></strong><p>87% of requests resolved within the service target.</p><div class="progress-track"><i style="--progress:87%"></i></div></div></section></div>
@endsection
