@extends('layouts.app')
@section('title', 'Dashboard — NEXA Desk')
@section('page-title', 'Dashboard')
@section('content')
@php
    $tickets = require resource_path('data/tickets.php');
    $mine = array_values(array_filter($tickets, fn ($ticket) => $ticket['email'] === 'user@nexadesk.com'));
    $open = count(array_filter($mine, fn ($ticket) => in_array($ticket['status'], ['New', 'Open', 'In Progress', 'Waiting', 'Escalated'], true)));
    $pending = count(array_filter($mine, fn ($ticket) => $ticket['status'] === 'Waiting'));
    $resolved = count(array_filter($mine, fn ($ticket) => $ticket['status'] === 'Resolved'));
    $closed = count(array_filter($mine, fn ($ticket) => $ticket['status'] === 'Closed'));
@endphp
<div class="page-heading"><div><span class="eyebrow">MONDAY, SEPTEMBER 28, 2026</span><h1>Welcome back, <span id="welcome-name">John</span>.</h1><p>Here is the latest on your support requests.</p></div><x-button href="{{ route('user.tickets.create') }}" variant="primary">＋ Create ticket</x-button></div>
<section class="stats-grid"><x-stat-card label="Open tickets" :value="$open" note="Requests in progress" icon="▤"/><x-stat-card label="Pending tickets" :value="$pending" note="Waiting for an update" icon="◷" tone="amber"/><x-stat-card label="Resolved" :value="$resolved" note="Ready to get back to work" icon="✓" tone="green"/><x-stat-card label="Closed" :value="$closed" note="Completed requests" icon="⌑" tone="blue"/></section>
<div class="dashboard-columns"><div class="dashboard-main"><section class="panel"><div class="panel-heading"><div><h2>Recent tickets</h2><p>Your most recent support requests</p></div><a class="subtle-link" href="{{ route('user.tickets') }}">View all tickets <span>→</span></a></div><div class="ticket-card-list" data-user-recent>@foreach (array_slice($mine, 0, 3) as $ticket)<x-ticket-card :ticket="$ticket"/>@endforeach</div></section><section class="panel activity-panel"><div class="panel-heading"><div><h2>Recent activity</h2><p>Updates from your support team</p></div><a class="subtle-link" href="{{ route('user.tickets') }}">Ticket history →</a></div><div class="activity-feed"><x-timeline-item title="Alex Morgan replied to NX-2026-004281" time="12 minutes ago" icon="↩" description="We are checking the VPN connection on your account."/><x-timeline-item title="NX-2026-004284 was assigned to IT Support" time="Yesterday, 10:18 AM" icon="＋"/><x-timeline-item title="NX-2026-004292 was resolved" time="Sep 24, 3:16 PM" icon="✓"/></div></section></div><aside class="dashboard-side"><section class="panel quick-actions"><div class="panel-heading"><div><h2>Quick actions</h2><p>What can we help with?</p></div></div><a href="{{ route('user.tickets.create') }}"><span class="quick-icon">＋</span><span><strong>Create ticket</strong><small>Tell us what you need</small></span><b>→</b></a><a href="{{ route('user.tickets') }}"><span class="quick-icon">▤</span><span><strong>My tickets</strong><small>Follow requests</small></span><b>→</b></a><a href="{{ route('user.knowledge') }}"><span class="quick-icon">◇</span><span><strong>Knowledge base</strong><small>Find a quick answer</small></span><b>→</b></a><a href="{{ route('user.notifications') }}"><span class="quick-icon">♧</span><span><strong>Notifications</strong><small>See what's changed</small></span><b>→</b></a></section><section class="panel announcement-panel"><div class="panel-heading"><div><h2>Announcements</h2><p>From the support team</p></div><span class="announcement-mark">◈</span></div><h3>Planned maintenance</h3><p>Core services are scheduled for maintenance tomorrow at 9:00 PM.</p><a class="subtle-link" href="{{ route('user.notifications') }}">Read the update →</a></section><section class="service-status"><span class="live-dot"></span><div><strong>All systems operational</strong><small>Last checked 2 minutes ago</small></div><a href="#service-status" aria-label="View service status">↗</a></section></aside></div>
@endsection
